version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surat_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - surat_network
    environment:
      DB_HOST: db
      DB_USER: amar
      DB_PASS: amar1403
      DB_NAME: suratdb

  db:
    image: mariadb:latest
    container_name: surat_db
    environment:
      MYSQL_ROOT_PASSWORD: amar1403
      MYSQL_DATABASE: suratdb
      MYSQL_USER: amar
      MYSQL_PASSWORD: amar
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - surat_network

networks:
  surat_network:
    driver: bridge
